MVCN2TST,TGC: add missing <limits> header
Fixes the following compile error:

    move-the-coins-2-test-testcase-generator.cpp:70:34: error: ‘numeric_limits’ is not a member of ‘std’
       70 | const int NoExplicitLimit = std::numeric_limits<int>::max();