COUNTREE,TGC: add missing <limits> header
Fixes the following compile error:

    counters-on-a-tree-testcase-generator.cpp:65:34: error: ‘numeric_limits’ is not a member of ‘std’
       65 | const int NoExplicitLimit = std::numeric_limits<int>::max();