EQUITREE,TGC: add missing <limits> header
Fixes the following compile error:

    equilateral-treeangles-testcase-generator.cpp:51:34: error: ‘numeric_limits’ is not a member of ‘std’
       51 | const int NoExplicitLimit = std::numeric_limits<int>::max();